/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.sessions;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum FreeCarfaxReport {
  t, f  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FreeCarfaxReport\",\"namespace\":\"com.refactorlabs.cs378.sessions\",\"symbols\":[\"t\",\"f\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
